name: windsurg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1.1
  - nltk=3.8.1
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - spacy=3.7.2
  - requests=2.31.0
  - beautifulsoup4=4.12.2
  - tqdm=4.66.1
  - pip=23.2
  - pip:
    - textblob==0.17.1
    - newspaper3k==0.2.8
    - googlesearch-python==1.2.3
    - newsapi-python==0.2.7
    - dash==2.14.1
    - plotly==5.18.0
